#include <stdio.h>
#include <string.h>
#define OPS \
    X(full_crc32) \
    X(full_crcccitt) \
    X(full_b64) \
    X(full_tv) \
    X(full_cdr) \
    X(full_cross) \
    X(full_os_string) \
    X(full_os_stdio) \
    X(full_os_stdlib) \
    X(full_os_ctype) \
    X(full_os_time) \
    X(full_os_math) \
    X(full_os_regex) \
    X(full_os_dirent) \
    X(full_os_pwd) \
    X(full_os_uname) \
    X(full_os_errno) \
    X(full_os_fdio) \
    X(full_os_stat) \
    X(full_os_gettod) \
    X(full_os_uio) \
    X(full_os_poll) \
    X(full_os_signal) \
    X(full_os_socket) \
    X(full_os_netdb) \
    X(full_os_mmap) \
    X(full_os_forkwait) \
    X(full_os_dlfcn) \
    X(full_os_sysv) \
    X(full_os_thread) \
    X(full_os_ioctl) \
    X(full_os_sendfile) \
    X(full_os_wchar) \
    X(full_cstring) \
    X(full_wstring) \
    X(full_array) \
    X(full_array_map) \
    X(full_map_manager) \
    X(full_hash_map) \
    X(full_rb_tree) \
    X(full_containers) \
    X(full_vector) \
    X(full_intrusive_list) \
    X(full_smart_ptr) \
    X(full_free_list) \
    X(full_obstack) \
    X(full_pair_env) \
    X(full_active_map) \
    X(full_ace_util) \
    X(full_mutex) \
    X(full_guard) \
    X(full_semaphore) \
    X(full_condition) \
    X(full_atomic) \
    X(full_thread_mgr) \
    X(full_barrier) \
    X(full_task) \
    X(full_activation_queue) \
    X(full_future) \
    X(full_tss) \
    X(full_sched) \
    X(full_test_and_set) \
    X(full_malloc_local) \
    X(full_allocator) \
    X(full_malloc_mmap) \
    X(full_mem_map) \
    X(full_shmem) \
    X(full_sysv_ipc) \
    X(full_message_block) \
    X(full_message_queue) \
    X(full_log_msg) \
    X(full_trace) \
    X(full_read_buffer) \
    X(full_addrs) \
    X(full_sock_stream) \
    X(full_sock_dgram) \
    X(full_lsock) \
    X(full_pipe) \
    X(full_fifo) \
    X(full_process) \
    X(full_process_sync) \
    X(full_cdr_stream) \
    X(full_get_opt) \
    X(full_timers_stats) \
    X(full_time_policy) \
    X(full_dll) \
    X(full_ace_misc2) \
    X(full_uuid) \
    X(full_date_time) \
    X(full_codeset) \
    X(full_capabilities) \
    X(full_notification_queue) \
    X(full_select_reactor) \
    X(full_tp_reactor) \
    X(full_dev_poll_reactor) \
    X(full_priority_reactor) \
    X(full_notification_strategy) \
    X(full_timer_queues) \
    X(full_proactor) \
    X(full_service_config) \
    X(full_configuration) \
    X(full_naming) \
    X(full_name_request) \
    X(full_event) \
    X(full_file_io) \
    X(full_dev_io) \
    X(full_tty_io) \
    X(full_mem_stream) \
    X(full_spipe) \
    X(full_upipe) \
    X(full_mcast_bcast) \
    X(full_seqpack) \
    X(full_ping) \
    X(full_netlink) \
    X(full_tokens) \
    X(full_filecache) \
    X(full_sbrk_pool) \
    X(full_shm_pool) \
    X(full_functors) \
    X(full_dynamic) \
    X(full_hashable) \
    X(full_recyclable) \
    X(full_stack_trace) \
    X(full_dump) \
    X(full_handle_ops) \
    X(full_tss_adapter) \
    X(full_thread_hook) \
    X(full_os_qos) \
    X(full_conn_recycling) \
    X(full_log_callback) \
    X(full_log_syslog) \
    X(full_logging_strategy) \
    X(full_log_category) \
    X(full_monitor) \
    X(full_assert) \
    X(full_dynamic_message) \
    X(full_dynamic_service) \
    X(full_lsock_codgram) \
    X(full_monitor_admin) \
    X(full_name_client) \
    X(full_cb_proactor) \
    X(full_service_manager) \
    X(full_copy_disabled) \
    X(full_rw_upgrade) \
    X(full_leaf_sweep) \

#define X(n) extern int op_##n(void);
OPS
#undef X
int main(int argc, char **argv){ const char*op=argc>1?argv[1]:"";
#define X(n) if(!strcmp(op,#n)){printf("%d\n",op_##n());return 0;}
OPS
#undef X
fprintf(stderr,"unknown op: %s\n",op); return 1; }
